In [4]:
#biblioteca de calculo
import numpy as np

#biblioteca para machine learning scikit-learn
from sklearn.datasets import load_iris # carregar os dados da base iris
from sklearn.model_selection import train_test_split # funçao para dividir a base em treino e teste
from sklearn.preprocessing import OneHotEncoder #função para normalização

#funções diversas da bibliotecas keras
from keras.models import Sequential # objeto que cria rede neural
from keras.layers import Dense # objeto ue cria camadas
from keras.optimizers import Adam # otimizador da rede neural


In [12]:
iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:7])
print('Example labels: ')
print(iris_data.target[48:115])

x = iris_data.data
y_= iris_data.target.reshape(-1, 1) # Convert data to a single column

# Normalização
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y[48:53])

# Dividir em Treino e Teste
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.30)

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]]
Example labels: 
[0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [14]:
#inicia a construção da rede neural
model = Sequential()

#adicionando camadas
#na primeira camada, é necessário definir o input_shape ( que deve ser igual ao numero de colunas no X)

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc11'))
model.add(Dense(15, activation='relu', name='fc22'))
#normalmente quando é um problema de classificação, utilizamos ativação softmax na ultima camada
model.add(Dense(3, activation='softmax', name='output'))

# O método compile recebe o otimizador, função loss e a métrica
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc11 (Dense)                 (None, 10)                50        
_________________________________________________________________
fc22 (Dense)                 (None, 15)                165       
_________________________________________________________________
output (Dense)               (None, 3)                 48        
Total params: 263
Trainable params: 263
Non-trainable params: 0
_________________________________________________________________
None


In [15]:
#treina o modelo usando um certo numero de iterações (épocas)
model.fit(train_x, train_y, verbose=2, epochs=200)

Epoch 1/200
4/4 - 0s - loss: 1.3636 - accuracy: 0.3429
Epoch 2/200
4/4 - 0s - loss: 1.3087 - accuracy: 0.3333
Epoch 3/200
4/4 - 0s - loss: 1.2581 - accuracy: 0.2762
Epoch 4/200
4/4 - 0s - loss: 1.2240 - accuracy: 0.0190
Epoch 5/200
4/4 - 0s - loss: 1.1861 - accuracy: 0.0000e+00
Epoch 6/200
4/4 - 0s - loss: 1.1611 - accuracy: 0.0000e+00
Epoch 7/200
4/4 - 0s - loss: 1.1387 - accuracy: 0.0095
Epoch 8/200
4/4 - 0s - loss: 1.1211 - accuracy: 0.0857
Epoch 9/200
4/4 - 0s - loss: 1.1078 - accuracy: 0.4857
Epoch 10/200
4/4 - 0s - loss: 1.0955 - accuracy: 0.4762
Epoch 11/200
4/4 - 0s - loss: 1.0848 - accuracy: 0.4286
Epoch 12/200
4/4 - 0s - loss: 1.0722 - accuracy: 0.3714
Epoch 13/200
4/4 - 0s - loss: 1.0601 - accuracy: 0.3714
Epoch 14/200
4/4 - 0s - loss: 1.0495 - accuracy: 0.3619
Epoch 15/200
4/4 - 0s - loss: 1.0377 - accuracy: 0.3619
Epoch 16/200
4/4 - 0s - loss: 1.0263 - accuracy: 0.3619
Epoch 17/200
4/4 - 0s - loss: 1.0189 - accuracy: 0.3524
Epoch 18/200
4/4 - 0s - loss: 1.0063 - accuracy: 

In [16]:
results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))


2/2 [==============================] - 0s 3ms/step - loss: 0.2550 - accuracy: 0.9556
Final test set loss: 0.255014
Final test set accuracy: 0.955556


In [ ]:
#
model.predict()

In [45]:

#train_y, test_y 
res=model.predict(test_x)
res2=res.astype(float)
np.set_printoptions(precision=8)
print(np.around(res2[:10],3))
#print(res2[:10])
print(test_y[:10])


ValueError: ignored

In [46]:
np.set_printoptions(precision=8)


In [ ]:
#exemplo de rede neural com regressao

In [9]:
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
import io
import requests
import numpy as np

In [10]:
url = "https://raw.githubusercontent.com/silviostanzani/PosBigData/master/Auto2.csv"
s = requests.get(url).content
dataframe = read_csv(io.StringIO(s.decode('utf-8')))
print(dataframe)
print(dataframe.columns)
dataset = dataframe.values

# split into input (X) and output (Y) variables
X_ = dataset[:,2:8]
y_ = dataset[:,1]
print(X)
print(y)

X = np.asarray(X_).astype(np.float32)
y = np.asarray(y_).astype(np.float32)

train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.20)

      mpg  cylinders  displacement  ...  year  origin                       name
0    18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1    15.0          8         350.0  ...    70       1          buick skylark 320
2    18.0          8         318.0  ...    70       1         plymouth satellite
3    16.0          8         304.0  ...    70       1              amc rebel sst
4    17.0          8         302.0  ...    70       1                ford torino
..    ...        ...           ...  ...   ...     ...                        ...
392  27.0          4         140.0  ...    82       1            ford mustang gl
393  44.0          4          97.0  ...    82       2                  vw pickup
394  32.0          4         135.0  ...    82       1              dodge rampage
395  28.0          4         120.0  ...    82       1                ford ranger
396  31.0          4         119.0  ...    82       1                 chevy s-10

[397 rows x 9 columns]
Inde

In [14]:
model = Sequential()

#model.add(Dense(20, input_dim=6, activation='relu'))
#model.add(Dense(1))
model.add(Dense(20, input_dim=6, kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))


# Compile model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse'])


In [15]:
model.fit(train_x, train_y, verbose=2, epochs=200)

#results = model.evaluate(test_x, test_y)

#print(results)

Epoch 1/200
10/10 - 0s - loss: 93.9336 - mse: 93.9336
Epoch 2/200
10/10 - 0s - loss: 27.3745 - mse: 27.3745
Epoch 3/200
10/10 - 0s - loss: 4.3642 - mse: 4.3642
Epoch 4/200
10/10 - 0s - loss: 4.4602 - mse: 4.4602
Epoch 5/200
10/10 - 0s - loss: 1.8018 - mse: 1.8018
Epoch 6/200
10/10 - 0s - loss: 0.8139 - mse: 0.8139
Epoch 7/200
10/10 - 0s - loss: 0.8581 - mse: 0.8581
Epoch 8/200
10/10 - 0s - loss: 0.7461 - mse: 0.7461
Epoch 9/200
10/10 - 0s - loss: 0.6802 - mse: 0.6802
Epoch 10/200
10/10 - 0s - loss: 0.6943 - mse: 0.6943
Epoch 11/200
10/10 - 0s - loss: 0.6679 - mse: 0.6679
Epoch 12/200
10/10 - 0s - loss: 0.6549 - mse: 0.6549
Epoch 13/200
10/10 - 0s - loss: 0.6534 - mse: 0.6534
Epoch 14/200
10/10 - 0s - loss: 0.6331 - mse: 0.6331
Epoch 15/200
10/10 - 0s - loss: 0.6136 - mse: 0.6136
Epoch 16/200
10/10 - 0s - loss: 0.6126 - mse: 0.6126
Epoch 17/200
10/10 - 0s - loss: 0.5954 - mse: 0.5954
Epoch 18/200
10/10 - 0s - loss: 0.6028 - mse: 0.6028
Epoch 19/200
10/10 - 0s - loss: 0.5661 - mse: 0.566

In [16]:
results = model.evaluate(test_x, test_y)

print(results)

3/3 [==============================] - 0s 2ms/step - loss: 0.3092 - mse: 0.3092
[0.30918702483177185, 0.30918702483177185]


In [19]:
#train_y, test_y 
res=model.predict(test_x)
#res2=res.astype(float)
np.set_printoptions(precision=0)
#print(np.around(res2[:10],3))
print(res[:10])
print(test_y[:10])

[[8.]
 [4.]
 [5.]
 [4.]
 [5.]
 [5.]
 [9.]
 [6.]
 [9.]
 [4.]]
[8. 4. 4. 4. 6. 4. 8. 6. 8. 4.]
